language: node_js
node_js:
  - '0.12'
before_install:
  - npm install -g travis-lint
  - travis-lint .travis.yml
  - npm install -g gulp-cli
  - npm install -g grunt-cli
  - npm install -g clever-cli
  - pushd scripts
  - chmod 777 setup.sh
  - popd
  - npm run-script bootstrap
env:
  - NODE_ENV=test; NODE_PATH=./lib/:./modules/
before_script:
